openapi: 3.0.0
info:
  version: 0.0.1
  title: MX HTTP Proxy API
  description: |
    Выполнение команд через REST API на сервере [Zultys MX](https://www.zultys.com/zultys-cloud-services/).
    Для отслеживания событий на сервере Zultys MX используются [Server-Sent Events API](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).

    # Errors
    Для возврата кода ошибки используются стандартные коды возврата HTTP:

    | Код   | Описание                                          |
    |-------|---------------------------------------------------|
    | `400` | ошибка разбора параметров запроса                 |
    | `401` | требуется токен с сессией                         |
    | `403` | сессия больше не действительна                    |
    | `404` | команда не поддерживается                         |
    | `415` | неподдерживаемый тип данных                       |
    | `500` | ошибка сервера MX                                 |
    | `502` | сервер MX недоступен или не отвечает на запросы   |
    | `504` | превышено время ожидания ответа от сервера MX     |

    Описание ошибки отдается в виде ответа:

        {
          "error": "MX response timeout"
        }

    В том случае, когда команда успешно выполнена, но не содержит данных для возврата,
    используется код окончания `204`.
    
  license:
    name: MIT
servers:
  - url: /
security:
  - SessionToken: []

paths:
  /login:
    post:
      operationId: Login
      tags: [Authorization]
      description: >-
        Осуществляет подключение к серверу MX и авторизует пользователя.
        В ответ возвращается информация об авторизованном пользователе и токен авторизации сессии,
        который необходимо использовать в заголовке авторизации во всех остальных запросах.
      security: []
      requestBody:
        description: параметры для авторизации пользователя на сервер MX
        required: true
        content:
          application/json:
            schema:
              type: object
              description: информация для авторизации соединения
              required:
                - login
                - password
              properties:
                login:
                  type: string
                  description: логин пользователя
                password:
                  type: string
                  format: password
                  description: пароль для авторизации
                type:
                  type: string
                  enum: [User, Server]
                  description: тип авторизации
                platform:
                  type: string
                  example: iPhone
                  description: название платформы
                version:
                  type: string
                  example: '7.0'
                  description: версия платформы
                clientType:
                  type: string
                  enum: [Mobile, Desktop, CRM]
                  description: тип клиента
                serverType:
                  type: string
                  enum: [SMS]
                  description: тип сервера
                loginCapab:
                  type: string
                  example: Audio|Video|Im|911Support|BinIm|WebChat
                  description: дополнительные параметры авторизации
                mediaCapab:
                  type: string
                  example: Voicemail|Fax|CallRec
                  description: дополнительные параметры поддержки данных
                abNotify:
                  type: boolean
                  description: уведомлять об изменении адресной книги
                forced:
                  type: boolean
                  description: завершить все другие сессии данного пользователя
                apiVersion:
                  type: integer
                  format: int32
                  description: поддерживаемая версия MX API
                  example: 11
              example:
                login: mxtest
                password: mx_password
                type: User
                platform: iPhone
                version: '7.0'
      responses:
        '200':
          description: возвращает токен сессии и информацию об авторизованном пользователе
          content:
            application/json:
              schema:
                type: object
                required: [token, api, mx]
                properties:
                  token:
                    type: string
                    description: токен с сессией
                    example: yGuVWEnStvR3kC8P
                  user:
                    type: string
                    description: уникальный идентификатор пользователя MX
                    example: '43892780091502529'
                  device:
                    type: string
                    description: внутренний номер пользователя MX
                    example: '271'
                  softPhonePwd:
                    type: string
                    description: пароль для авторизации SIP
                    example: Pf3Hs4lLcWRpkYRK4MMbBQ1ZF1gI0WDX
                  api:
                    type: integer
                    format: int32
                    description: серверная версия MX API
                    example: 11
                  mx:
                    type: string
                    description: уникальный идентификатор MX
                    example: 631HC
                  maxMsgFileSizeMb:
                    type: integer
                    format: int32
                    description: максимально допустимый размер сообщения в мегабайтах
                  capab:
                    type: string
                    description: поддерживаемые дополнительные опции сервера
                example:
                  token: PGg_bXw8TdBKpSVX
                  sn: 631HC
                  apiVersion: 12
                  ext: '273'
                  jid: '43892780322813134'
                  softPhonePwd: lefIQ43upsZ4dSJ9saGzA5rkAcF2WBJl
        default:
          $ref: '#/components/responses/error'
  /logout:
    post:
      operationId: Logout
      tags: [Authorization]
      description: >-
        Завершает сессию и отключается от сервера MX. Авторизационный токен после 
        этого становится недействительным.
      responses:
        '204':
          $ref: '#/components/responses/204'
        default:
          $ref: '#/components/responses/error'

  /startMonitor:
    post:
      operationId: StartMonitor
      tags: [Events]
      description: >-
        Запуск серверного монитора позволяет отслеживать события о звонках.
        Так же без запущенного монитора недоступны многие операции. Например,
        работа с голосовой почтой.
      requestBody:
        description: параметры для запуска монитора
        required: true
        content:
          application/json:
            schema:
              type: object
              description: параметры запуска монитора
              required: [device]
              properties:
                device:
                  type: string
                  description: идентификатор устройства
                conf:
                  type: boolean
                  description: отслеживать события конференции
              example:
                device: '199'
      responses:
        '200':
          description: возвращает информацию о запущенном мониторе
          content:
            application/json:
              schema:
                type: object
                description: информация о запущенном мониторе
                required: [monitor]
                properties:
                  monitor:
                    type: integer
                    description: идентификатор монитора
                example:
                  monitor: 1
        default:
          $ref: '#/components/responses/error'
  /stopMonitor:
    post:
      operationId: StopMonitor
      tags: [Events]
      description: Останавливает ранее запущенный серверный монитор
      requestBody:
        description: параметры для остановки монитора
        content:
            application/json:
              schema:
                type: object
                description: параметры для остановки ранее запущенного монитора
                required: [monitor]
                properties:
                  monitor:
                    type: integer
                    description: идентификатор монитора
                example:
                  monitor: 1
      responses:
        '204':
          $ref: '#/components/responses/204'
        default:
          $ref: '#/components/responses/error'
  /startMonitorAb:
    post:
      operationId: StartMonitorAb
      tags: [Events]
      description: Запускает мониторинг изменений адресной книги
      responses:
        '204':
          $ref: '#/components/responses/204'
        default:
          $ref: '#/components/responses/error'
  /stopMonitorAb:
    post:
      operationId: StopMonitorAb
      tags: [Events]
      description: Останавливает мониторинг изменений адресной книги
      responses:
        '204':
          $ref: '#/components/responses/204'
        default:
          $ref: '#/components/responses/error'

  /events:
    post:
      operationId: Events
      tags: [Events]
      description: | 
        Отдает информацию о серверных событиях в формате 
        [Server-Sent Events](//developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).
      responses:
        '200':
          description: возвращает информацию о серверных событиях
          content:
            text/event-stream:
              schema:
                anyOf:
                  - title: presence
                    type: object
                    description: presence
                    properties:
                      user:
                        type: string
                        description: from
                      status:
                        type: string
                        description: mxStatus
                      presence:
                        type: string
                        description: presence
                      note:
                        type: string
                        description: presenceNote
                    example:
                      user: '44007001373183196'
                      presence: Available
                      status: USER_HAS_RINGING_CALL|USER_ON_CALL_NO_MORE_LINES
                      note: sample
                  - title: message
                    type: object
                    description: messageHist & message
                    required: [id, from, to]
                    properties:
                      id:
                        type: integer
                        format: int32
                        description: msgId
                      gid:
                        type: integer
                        description: persistId
                      new:
                        type: boolean
                        description: флаг, что сообщение не из истории
                        default: true
                      from:
                        type: string
                        description: from
                        example: '43892780838802510'
                      fromName:
                        type: string
                        description: name
                      to:
                        type: string
                        description: toRecipId
                        example: '43892780838802510'
                      toName:
                        type: string
                        description: toRecipName
                      group:
                        type: string
                        description: groupId
                        example: '43892780838802510'
                      did:
                        type: string
                        description: did
                      req:
                        type: integer
                        description: reqId
                      delivered:
                        type: boolean
                        description: delivered
                      seen:
                        type: boolean
                        description: seen
                      recipType:
                        type: string
                        description: recipType
                        enum: [User, Server, Group]
                      type:
                        type: string
                        description: packetType
                        enum: [Text, Binary, Conf]
                      timestamp:
                        type: integer
                        format: date-time
                        description: timestamp
                      finished:
                        type: boolean
                        description: finished
                      contentState:
                        type: string
                        description: contentState
                      contentSize:
                        type: integer
                        format: int32
                        description: contentSize
                  - title: messageHist
                    type: object
                    description: messageHist & message
                    required: [id, from, to]
                    properties:
                      id:
                        type: integer
                        format: int32
                        description: msgId
                      gid:
                        type: integer
                        description: persistId
                      new:
                        type: boolean
                        description: флаг, что сообщение не из истории
                        default: false
                      from:
                        type: string
                        description: from
                        example: '43892780838802510'
                      fromName:
                        type: string
                        description: name
                      to:
                        type: string
                        description: toRecipId
                        example: '43892780838802510'
                      toName:
                        type: string
                        description: toRecipName
                      group:
                        type: string
                        description: groupId
                        example: '43892780838802510'
                      did:
                        type: string
                        description: did
                      req:
                        type: integer
                        description: reqId
                      delivered:
                        type: boolean
                        description: delivered
                      seen:
                        type: boolean
                        description: seen
                      recipType:
                        type: string
                        description: recipType
                        enum: [User, Server, Group]
                      type:
                        type: string
                        description: packetType
                        enum: [Text, Binary, Conf]
                      timestamp:
                        type: integer
                        format: date-time
                        description: timestamp
                      finished:
                        type: boolean
                        description: finished
                      contentState:
                        type: string
                        description: contentState
                      contentSize:
                        type: integer
                        format: int32
                        description: contentSize
                  - title: DivertedEvent
                    type: object
                    description: >-
                      DivertedEvent indicates that a call has been diverted from a
                      device and that the call is no longer present at the device.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      diverting:
                        type: string
                        description: divertingDevice>deviceIdentifier
                      to:
                        type: string
                        description: newDestination>deviceIdentifier
                      cause:
                        type: string
                        description: cause
                      allowed:
                        type: integer
                        format: int32
                        description: cmdsAllowed
                      flags:
                        type: integer
                        description: callTypeFlags
                    example:
                      monitor: 1
                      call:
                        id: 351
                        device: '199'
                      diverting: '199'
                      to: '199'
                      cause: normal
                      allowed: 272
                      flags: 137363459
                  - title: DeliveredEvent
                    type: object
                    description: >-
                        DeliveredEvent indicates that a call is being presented
                        to a device in either the Ringing or Entering distribution
                        modes of the alerting state.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      alerting:
                        type: string
                        description: alertingDevice>deviceIdentifier
                      alertingName:
                        type: string
                        description: alertingDisplayName
                      networkCalling:
                        type: string
                        description: networkCallingDevice>deviceIdentifier
                      calling:
                        type: string
                        description: callingDevice>deviceIdentifier
                      callingName:
                        type: string
                        description: callingDisplayName
                      called:
                        type: string
                        description: calledDevice>deviceIdentifier
                      lastRedirection:
                        type: string
                        description: lastRedirectionDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                      allowed:
                        type: integer
                        format: int32
                        description: cmdsAllowed
                      flags:
                        type: integer
                        format: int32
                        description: callTypeFlags
                      cads:
                        type: array
                        items:
                          $ref: '#/components/schemas/Cad'
                    example:
                      monitor: 1
                      call:
                        id: 351
                        device: '199'
                        global: '2809269720623105293'
                      alerting: '*86'
                      alertingName: voicemail
                      networkCalling: Vasily Znamensky
                      calling: '192'
                      callingName: Vasily Znamensky
                      called: '*86'
                      lastRedirection: ''
                      localConnection: alerting
                      cause: normal
                      flags: 3145736
                      cads:
                        - name: __FIRST_CALL_ID__
                          type: string
                          value: 631UN-B5-00004-50E
                  - title: EstablishedEvent
                    type: object
                    description: >-
                      EstablishedEvent indicates that a call has been answered
                      at a device or that a call has been connected to a device.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      answering:
                        type: string
                        description: answeringDevice>deviceIdentifier
                      answeringName:
                        type: string
                        description: answeringDisplayName
                      calling:
                        type: string
                        description: callingDevice>deviceIdentifier
                      callingName:
                        type: string
                        description: callingDisplayName
                      called:
                        type: string
                        description: calledDevice>deviceIdentifier
                      lastRedirection:
                        type: string
                        description: lastRedirectionDevice>deviceIdentifier
                      cause:
                        type: string
                        description: cause
                      allowed:
                        type: integer
                        format: int32
                        description: cmdsAllowed
                      flags:
                        type: integer
                        format: int32
                        description: callTypeFlags
                      cads:
                        type: array
                        items:
                          $ref: '#/components/schemas/Cad'
                    example:
                      monitor: 1
                      call:
                        id: 5
                        device: '199'
                        global: '2809269720623105284'
                      answering: '199'
                      answeringName: Maxim Donchenko
                      calling: '192'
                      callingName: Vasily Znamensky
                      called: '*86'
                      calledName: voicemail
                      lastRedirection: ''
                      cause: normal
                      flags: 137371651
                      cads:
                        - name: __FIRST_CALL_ID__
                          type: string
                          value: 631UN-B5-00004-504
                  - title: HeldEvent
                    type: object
                    description: HeldEvent indicates that a call has been placed on hold.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      holding:
                        type: string
                        description: holdingDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                      allowed:
                        type: integer
                        format: int32
                        description: cmdsAllowed
                      flags:
                        type: integer
                        format: int32
                        description: callTypeFlags
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      holding: '199'
                      cause: normal
                      allowed: 376
                      flags: 141565955
                  - title: RecordingStateEvent
                    type: object
                    description: RecordingStateEvent
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      available:
                        type: boolean
                        description: RecIsAvailable
                      active:
                        type: boolean
                        description: RecIsActive
                    example:
                      monitor: 1
                      call:
                        id: 18
                        device: '199'
                      available: true
                      active: false
                  - title: ServiceInitiatedEvent
                    type: object
                    description: >-
                      ServiceInitiatedEvent indicates that a telephony service has been
                      initiated at a monitored device.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      initiating:
                        type: string
                        description: initiatingDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      localConnection: initializing
                      initiating: '199'
                      cause: normal
                  - title: ConnectionClearedEvent
                    type: object
                    description: >-
                      ConnectionClearedEvent indicates that a call has been cleared and no
                      longer exists.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      releasing:
                        type: string
                        description: releasingDevice>deviceIdentifier
                      cause:
                        type: string
                        description: cause
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      releasing: '199'
                      cause: normal
                  - title: OriginatedEvent
                    type: object
                    description: >-
                      OriginatedEvent indicates that a call is being attempted
                      from a device.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      calling:
                        type: string
                        description: callingDevice>deviceIdentifier
                      called:
                        type: string
                        description: calledDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                      allowed:
                        type: integer
                        format: int32
                        description: cmdsAllowed
                      flags:
                        type: integer
                        format: int32
                        description: callTypeFlags
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      calling: '199'
                      called: '192'
                      cause: normal
                      flags: 3145728
                  - title: NetworkReachedEvent
                    type: object
                    description: >- 
                      NetworkReachedEvent indicates that a call has cut
                      through the switching sub-domain boundary to another network.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      network:
                        type: string
                        description: networkInterfaceUsed>deviceIdentifier
                      calling:
                        type: string
                        description: callingDevice>deviceIdentifier
                      called:
                        type: string
                        description: calledDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      network: '190'
                      calling: '199'
                      called: '192'
                      cause: normal
                  - title: FailedEvent
                    type: object
                    description: >- 
                      FailedEvent indicates that a call cannot be completed or a
                      connection has entered the Failed state.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      calling:
                        type: string
                        description: callingDevice>deviceIdentifier
                      called:
                        type: string
                        description: calledDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      calling: '199'
                      called: '192'
                      localConnection: ''
                      cause: normal
                  - title: RetrievedEvent
                    type: object
                    description: >- 
                      RetrievedEvent indicates that a previously held call has been
                      retrieved.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      retrieving:
                        type: string
                        description: retrievingDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                      allowed:
                        type: integer
                        format: int32
                        description: cmdsAllowed
                      flags:
                        type: integer
                        format: int32
                        description: callTypeFlags
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      retrieving: '199'
                      localConnection: ''
                      cause: normal
                      flags: 3145728
                  - title: TransferredEvent # в xml название события с ошибкой: одна буква r
                    type: object
                    description: >-
                      TransferedEvent indicates that an existing call has been
                      transferred to another device and the transferring device has
                      been dropped from the call.
                    required: [monitor, call]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      call:
                        $ref: '#/components/schemas/Call'
                      transferring:
                        type: string
                        description: transferringDevice>deviceIdentifier
                      to:
                        type: string
                        description: transferredToDevice>deviceIdentifier
                      localConnection:
                        type: string
                        description: localConnectionInfo
                      cause:
                        type: string
                        description: cause
                    example:
                      monitor: 1
                      call:
                        id: 56
                        device: '199'
                      transferring: '199'
                      to: '198'
                      localConnection: ''
                      cause: normal
                      flags: 3145728
                  - title: ParkedEvent
                    type: object
                    description: callParkInfo
                    required: [monitor, park]
                    properties:
                      monitor:
                        type: integer
                        format: int32
                        description: monitorCrossRefID
                      park: 
                        type: integer
                        format: int32
                        description: parkID
                    example:
                      monitor: 1
                      park: 3
              example: |
                  event: presence
                  data: {"presence":"Available","status":"USER_ACCEPTS_IM","note":"Заметка к статусу"}
                      
                  event: ConnectionClearedEvent
                  data: {"monitor":1,"call":{"id":56,"device":"199"},"releasing":"199","cause":"normal"}
        default:
          $ref: '#/components/responses/error'

components:
  securitySchemes:
    SessionToken:
      type: http
      scheme: bearer
      description: |
        Токен сессии возвращается при авторизации пользователя ([`/login`](#operation/Login)) 
        и действителен до тех пор, пока сервер поддерживает соединение с MX или не выполнена команда 
        [`/logout`](#operation/Logout). После этого необходимо заново авторизоваться и получать новый токен с 
        идентификатором сесии.

        Данный токен необходимо использовать для все запросов API, кроме непосредственно
        запроса авторизации:

            Authorization: Bearer LRSO4vGDdyLA6UQl

        В качестве альтернативы, токен авторизации можно передавать не в заголовке, а
        в виде параметра запроса `?access_token=...`. Данный подход можно использовать,
        например, при создании запроса на получение событий сервера MX с помощью 
        [HTTP Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).

  schemas:
    Call:
      title: call
      type: object
      description: Описывает информацию о звонке
      required: [id, device]
      properties:
        id: 
          type: integer
          format: int32
          description: callID
        device:
          type: string
          description: deviceID
        global:
          type: string
          description: globalCallID
      example:
        id: 18
        device: '234'
    Cad:
      title: cad
      type: object
      required: [name, type, value]
      properties:
        name:
          type: string
          description: name
        type:
          type: string
          description: type
        value:
          type: string
          description: value

  responses:
    '204':
      description: успешное выполнение команды
    error: 
      description: ошибка выполнения команды
      content:
        application/json:
          schema:
            description: формат возвращаемой ошибки
            type: object
            required:
              - error
            properties:
              error:
                type: string
                description: описание ошибки
                example: MX error
